name: nix-build-latest
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
        extra_nix_config: |
          extra-platforms = aarch64-linux

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - run: nix-build '<nixpkgs/nixos>' -A config.system.build.sdImage -I nixos-config=./configuration.default.sdImage.nix --option sandbox false
    - uses: actions/upload-artifact@v2
      with:
        name: sd-image.img
        path: ./result/sd-image/*.img